name: flutter_packages
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  photo_view: ^0.13.0
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  #assets:
  #   - assets/videos/video.mp4

  # example:


